os: linux
dist: xenial
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
script:
- hugo version
- hugo
before_deploy:
- openssl aes-256-cbc -K $encrypted_711f30a834c1_key -iv $encrypted_711f30a834c1_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.63.1
  - secure: M8l4/uMjQUfNa5xYZTttfGs8DguC6FJDqTdDrWx2aVgVJO8+Ux8y8SmCETPT9loOFxGLf4pgeecH9Svl0ctRbkLZEU4Ga2bg5m4flj6mv2fFnrCr3zNbevqm6fgXCMl8hd11QfDtB8D3UnOrPUSeLE/RD6VWcLaljx7W0XsKQu7rP44TDYXwzF8LkPxkb5r6IeeWNJeGDeuTOKjBactS3gsRVZP/zbpJshmlyZylWOqxavX/VODFNoSyn+uK0T/DOlcoQ9s5GPixRiFdj12l6Bh61ioaWLzxtsFjXraIKb1iPshpNj9YqOHd/Wu8PEaoO6+wiQue9cYZDVaqxps4RJlOP8WLIR7GgRRP2JbzKChPZC7I0qotiDdEzjbzPgIVqVZomHD/1rIBV3Xz8FFQt268Ly1ybUjDBVlF89vCys76slqC3BYOiCWLpeggE1un+h272caSCxzp/rxIk3boARox4NoUAGWI5EAi1171Bo84oUztVwZ5DFN3ZQ29isHrjkUndcFjUltMeMcA4BVmbvFAls8BUCL3SclTW+GzUBU2nhZYfEoyuOyxOwoflLW5eePWaZ7YUw51Xq9NgTNAaJHgWLfQ7q/P5owS3ynnvXnZoWHY5uA88iLvdReJ4ss0twmrrFXPVDnEVVLSrl/uuO9g6xVbqkh/NlG+46g9xDo=
  - secure: UfxuIqmiNAeXW6AjofzdSpk4IVFn1v0iWaQfTw4CHgCDWWOav1kCiBvvwS/D4QTqCQC0C5Y5GmAB8s89751zqiNYdnlUlGDgHFFm+527EPSgkVLtdroxWrMX2Pd3RNQhdosBFEyLkEHdYdpJ7od4orLKg6GWTEJPHen7a3h0+rW18SfRMmYxfBBAuPWgVILgodVgdoNMUCIC1JFLUgs/r5mywl8Fc7zd7XWvzBXM4T2llv8yLkhz9MqofIKim4FKeLfnI6KR/stGfEpiTCjy9+5DtmlC0gCtWrvZTNZqxiHMhpmVJ+th5CMbcAf9h276EPOof/cRDMg6oUgw2cYzlF9tNP1nQ3uk7CP14T7vJM+hmCqJpApYJxsMpMYTBvJEwMcEdOjOs0NEkUNZ3wU4MWTGPt2n3/p8jYLYm8MOQMAEpIJBeQbMVRH8CPy5M2iCwRr6JOaxNA3glqGmQ0t5o7JnUTgp4yDVGmlj4hC7PxH6XzeT8RZU1CyjobyYOKF+v9BGcb+yieK1uFKhgb1qOcCDLr19G1FliZ8QWHWLY5TCgn2JpU6JvKEHNi/NhdGFypmPDLNSk56b/VYBixHaguOyk/PY0+mnYJ4SXZXFZirwN0TnzR8MDdCHlsDyzWyfBFqCcChxXH8IuWTAIijYxWCuAJ8UBlSMfhsyoEPJVf4=
  - secure: at5mI0nIYdWugkhl1CfqbIqEoCIlA5ApLKx+2pvRMgekZAAep59YtFX9Q/KHgUfwyyMNU+VyORJCZwqF5V84eVMn1Q9idZr5ysTRChyOBw7a13hAFEJJPxSSCYhlJAaXDGaZi/8GUL3KJbyPw2tmtBubc/9+xx9adTDtNGVPLZruJgUHgyS+r7SlLpmOCo03ZysBhB01aSkDupPNNOHxiqYV2Ul+EOKKbBhKN7jpcxsUsZofptVNrXYBnjF3Xpg5fGZZ9zRo0rSQVX1HGkCXASw/hCe8yaw7lVSYCj/k95410Tc3afiCBE2w8GO9nUqqplf9WxpH8/uH+bOu/1PAZaS6Kho0vuivqRJ6Y6NkBXBi+/lcQ6rwYnoV6xXsRrmxJbPYMHsQiDC/pJTOzuA3f2nu/HA326qUX141s+mynAGXvctR/0uOqHq1kUBY15+Sb2FJozenQyehVhOT1RD5rInx0zPNSzZ560LVe/kdV/2uDxLPKOBPOYhAvvTOXdPqhybLdXryJyhSHPHMg4Ph7qfDlUGH2kzpbLgVVckyOlycv7rejHVx3raCRGxal8y//RoEWLHFM6M8JJjB+O70vlU3Q0Csb2r49qACMSDGRwi9BnsO/sNKUb2fsac2DPLTTduVyuGVFKfTOLz+rHq+K6FHZq1IPa6/9Uy00rIalTA=
